:bug: fix doc test
Since the version is not specified, the latest `streamtools@v1.0.0` is
referenced. However, since this version supports JSR, the following
error occurs in doctest.

```
error: Relative import path "@std/bytes" not prefixed with / or ./ or ../
    at https://deno.land/x/streamtools@v1.0.0/read_all.ts:1:24
```